'use strict';
/**
 * Sitemap + report builders. Pure functions, no Electron dependency.
 */
const MAX_URLS_PER_SITEMAP = 50000;

function xmlEscape(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function htmlEscape(s) {
  return xmlEscape(s);
}

function priorityForDepth(depth) {
  const p = 1.0 - depth * 0.2;
  return Math.max(0.3, Math.round(p * 10) / 10).toFixed(1);
}

/** Pages eligible for the sitemap: 2xx HTML, not noindex. */
function indexablePages(pages) {
  return pages.filter(
    (p) => p.status >= 200 && p.status < 300 && !p.noindex && (p.contentType || '').includes('html') && !p.error
  );
}

function lastmodOf(page, fallbackIso) {
  if (page.lastMod) {
    const d = new Date(page.lastMod);
    if (!isNaN(d)) return d.toISOString().slice(0, 10);
  }
  return (fallbackIso || new Date().toISOString()).slice(0, 10);
}

/**
 * Build sitemap XML file(s). Returns array of { filename, content } plus
 * an optional sitemap index when > 50k URLs.
 * @param {Array} pages crawl pages
 * @param {object} opts { crawledAt, baseUrl } baseUrl used for index file loc entries
 */
function buildSitemapFiles(pages, opts = {}) {
  const eligible = indexablePages(pages);
  const crawledAt = opts.crawledAt || new Date().toISOString();
  const urlEntry = (p) =>
    `  <url>\n    <loc>${xmlEscape(p.url)}</loc>\n    <lastmod>${lastmodOf(p, crawledAt)}</lastmod>\n    <priority>${priorityForDepth(p.depth || 0)}</priority>\n  </url>`;

  const wrap = (entries) =>
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries.join('\n')}\n</urlset>\n`;

  if (eligible.length <= MAX_URLS_PER_SITEMAP) {
    return [{ filename: 'sitemap.xml', content: wrap(eligible.map(urlEntry)) }];
  }

  // Split into chunks + sitemap index
  const files = [];
  const chunks = [];
  for (let i = 0; i < eligible.length; i += MAX_URLS_PER_SITEMAP) {
    chunks.push(eligible.slice(i, i + MAX_URLS_PER_SITEMAP));
  }
  const base = (opts.baseUrl || (eligible[0] ? new URL(eligible[0].url).origin : '')).replace(/\/$/, '');
  const today = crawledAt.slice(0, 10);
  const indexEntries = [];
  chunks.forEach((chunk, i) => {
    const name = `sitemap-${i + 1}.xml`;
    files.push({ filename: name, content: wrap(chunk.map(urlEntry)) });
    indexEntries.push(
      `  <sitemap>\n    <loc>${xmlEscape(base + '/' + name)}</loc>\n    <lastmod>${today}</lastmod>\n  </sitemap>`
    );
  });
  files.unshift({
    filename: 'sitemap.xml',
    content: `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${indexEntries.join('\n')}\n</sitemapindex>\n`,
  });
  return files;
}

/** Human-readable HTML sitemap grouped by depth. */
function buildSitemapHtml(pages, opts = {}) {
  const eligible = indexablePages(pages);
  const site = opts.siteName || (eligible[0] ? new URL(eligible[0].url).hostname : 'Site');
  const byDepth = new Map();
  for (const p of eligible) {
    const d = p.depth || 0;
    if (!byDepth.has(d)) byDepth.set(d, []);
    byDepth.get(d).push(p);
  }
  const sections = [...byDepth.keys()]
    .sort((a, b) => a - b)
    .map((d) => {
      const items = byDepth
        .get(d)
        .map(
          (p) =>
            `      <li><a href="${htmlEscape(p.url)}">${htmlEscape(p.title || p.url)}</a></li>`
        )
        .join('\n');
      return `  <section>\n    <h2>${d === 0 ? 'Home' : `Level ${d}`}</h2>\n    <ul>\n${items}\n    </ul>\n  </section>`;
    })
    .join('\n');
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Sitemap — ${htmlEscape(site)}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;max-width:860px;margin:2rem auto;padding:0 1rem;color:#1a1a2e;line-height:1.6}
  h1{border-bottom:2px solid #eee;padding-bottom:.5rem}
  h2{color:#555;font-size:1rem;text-transform:uppercase;letter-spacing:.05em;margin-top:2rem}
  ul{columns:2;gap:2rem;padding-left:1.2rem}
  a{color:#2563eb;text-decoration:none}
  a:hover{text-decoration:underline}
  footer{margin-top:3rem;color:#999;font-size:.8rem}
</style>
</head>
<body>
<h1>Sitemap — ${htmlEscape(site)}</h1>
<p>${eligible.length} pages · generated ${new Date().toISOString().slice(0, 10)} with Maptrail</p>
${sections}
<footer>Generated by Maptrail — pay once, own it forever.</footer>
</body>
</html>
`;
}

/** Full crawl report CSV — every crawled URL, indexable or not. */
function buildCsv(pages) {
  const cols = ['url', 'status', 'depth', 'title', 'meta_description', 'meta_desc_length', 'h1', 'word_count', 'canonical', 'noindex', 'content_type', 'error'];
  const esc = (v) => {
    const s = v === null || v === undefined ? '' : String(v);
    return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const rows = pages.map((p) =>
    [p.url, p.status, p.depth, p.title, p.metaDesc, p.metaDescLength, p.h1, p.wordCount, p.canonical, p.noindex ? 'yes' : 'no', p.contentType, p.error || ''].map(esc).join(',')
  );
  return cols.join(',') + '\n' + rows.join('\n') + '\n';
}

module.exports = { buildSitemapFiles, buildSitemapHtml, buildCsv, indexablePages, MAX_URLS_PER_SITEMAP, priorityForDepth };
